<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.osgi</groupId>
		<artifactId>org.osgi.service.metatype.annotations.reactor</artifactId>
		<version>${revision}</version>
	</parent>
	<groupId>org.osgi.tck</groupId>
	<artifactId>org.osgi.tck.service.metatype.annotations</artifactId>
	<packaging>pom</packaging>

	<modules>
		<module>org.osgi.test.cases.metatype.annotations</module>
		<module>org.osgi.impl.bundle.metatype.annotations</module>
		<module>org.osgi.test.run.metatype.annotations</module>
	</modules>

</project>
